export const assets = {
  brand: {
    logo: "/assets/brand/arc-logo.svg",
    logoMark: "/assets/brand/arc-logo-mark.png",
    icon: "/assets/brand/arc-icon.svg",
    appIcon: "/assets/brand/arc-app-icon.png",
    wordmark: "/assets/brand/arc-wordmark.svg",
    checkEmail: "/assets/brand/check-email.png",
  },
  arlo: {
    welcome: "/assets/arlo/arlo-welcome.png",
    envelope: "/assets/arlo/arlo-envelope.png",
    thumbsUp: "/assets/arlo/arlo-thumbs-up.png",
    waveHand: "/assets/arlo/arlo-wave-hand.png",
    celebrate: "/assets/arlo/arlo-celebrate.png",
    thinking: "/assets/arlo/arlo-thinking.png",
    sleepy: "/assets/arlo/arlo-sleepy.png",
    boss: "/assets/arlo/arlo-boss.png",
    roast: "/assets/arlo/arlo-roast.png",
    graduation: "/assets/arlo/arlo-graduation.png",
    /** Home hero — falls back to wave until dedicated art lands */
    home: "/assets/arlo/arlo-wave-hand.png",
    /** Arlo Says panel — falls back to thinking pose */
    wand: "/assets/arlo/arlo-thinking.png",
    /** Notifications / point pose — falls back to thumbs-up */
    point: "/assets/arlo/arlo-thumbs-up.png",
  },
  home: {
    chest: "/assets/home/chest.svg",
    wheel: "/assets/home/wheel.svg",
    prizeWheel: "/assets/home/prize-wheel.png",
    badges: "/assets/home/badges.svg",
    ninja: "/assets/home/ninja.svg",
  },
  backgrounds: {
    mountainWelcome: "/assets/backgrounds/mountain-welcome.png",
    authClouds: "/assets/backgrounds/auth-clouds.png",
    roadmapWorld: "/assets/backgrounds/roadmap-world.png",
    rewardBurst: "/assets/backgrounds/reward-burst.png",
    bossBg: "/assets/backgrounds/boss-bg.png",
  },
  icons: {
    apple: "/assets/icons/apple.svg",
    google: "/assets/icons/google.svg",
    xp: "/assets/icons/xp.svg",
    gem: "/assets/icons/gem.svg",
    coin: "/assets/icons/coin.svg",
    chest: "/assets/icons/chest.svg",
    badge: "/assets/icons/badge.svg",
    streak: "/assets/icons/streak.svg",
  },
  badges: {
    firstStep: "/assets/badges/first-step.png",
    weeklyWarrior: "/assets/badges/weekly-warrior.png",
    sqlSpark: "/assets/badges/sql-spark.png",
    comebackEagle: "/assets/badges/comeback-eagle.png",
    nightOwl: "/assets/badges/night-owl.png",
    earlyBird: "/assets/badges/early-bird.png",
    quizCrusher: "/assets/badges/quiz-crusher.png",
    projectStarter: "/assets/badges/project-starter.png",
    fourWeekFlame: "/assets/badges/four-week-flame.png",
    jobReadyEagle: "/assets/badges/job-ready-eagle.png",
  },
  chests: {
    common: "/assets/chests/common-chest.png",
    weekly: "/assets/chests/weekly-chest.png",
    boss: "/assets/chests/boss-chest.png",
    legendary: "/assets/chests/legendary-chest.png",
  },
} as const;
